// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createMetric = `-- name: CreateMetric :exec
INSERT INTO metrics (id, url_id, user_id, browser, os, device, language, referrer, country, region, city, utm)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateMetricParams struct {
	ID       string          `json:"id"`
	UrlID    sql.NullString  `json:"url_id"`
	UserID   string          `json:"user_id"`
	Browser  sql.NullString  `json:"browser"`
	Os       sql.NullString  `json:"os"`
	Device   sql.NullString  `json:"device"`
	Language sql.NullString  `json:"language"`
	Referrer sql.NullString  `json:"referrer"`
	Country  sql.NullString  `json:"country"`
	Region   sql.NullString  `json:"region"`
	City     sql.NullString  `json:"city"`
	Utm      json.RawMessage `json:"utm"`
}

func (q *Queries) CreateMetric(ctx context.Context, arg CreateMetricParams) error {
	_, err := q.db.ExecContext(ctx, createMetric,
		arg.ID,
		arg.UrlID,
		arg.UserID,
		arg.Browser,
		arg.Os,
		arg.Device,
		arg.Language,
		arg.Referrer,
		arg.Country,
		arg.Region,
		arg.City,
		arg.Utm,
	)
	return err
}

const getAggregateMetrics = `-- name: GetAggregateMetrics :many
SELECT url_id, browser, os, device, country, COUNT(*) as count
FROM metrics
WHERE ($1::timestamptz IS NULL OR timestamp >= $1)
  AND ($2::timestamptz IS NULL OR timestamp <= $2)
  AND ($3::text IS NULL OR url_id = $3)
GROUP BY url_id, browser, os, device, country
`

type GetAggregateMetricsParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 time.Time `json:"column_2"`
	Column3 string    `json:"column_3"`
}

type GetAggregateMetricsRow struct {
	UrlID   sql.NullString `json:"url_id"`
	Browser sql.NullString `json:"browser"`
	Os      sql.NullString `json:"os"`
	Device  sql.NullString `json:"device"`
	Country sql.NullString `json:"country"`
	Count   int64          `json:"count"`
}

func (q *Queries) GetAggregateMetrics(ctx context.Context, arg GetAggregateMetricsParams) ([]GetAggregateMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAggregateMetrics, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAggregateMetricsRow
	for rows.Next() {
		var i GetAggregateMetricsRow
		if err := rows.Scan(
			&i.UrlID,
			&i.Browser,
			&i.Os,
			&i.Device,
			&i.Country,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsByURL = `-- name: GetMetricsByURL :many
SELECT id, url_id, user_id, browser, os, device, language, referrer, country, region, city, utm, timestamp FROM metrics
WHERE url_id = $1
  AND ($2::timestamptz IS NULL OR timestamp >= $2)
  AND ($3::timestamptz IS NULL OR timestamp <= $3)
ORDER BY timestamp DESC
`

type GetMetricsByURLParams struct {
	UrlID   sql.NullString `json:"url_id"`
	Column2 time.Time      `json:"column_2"`
	Column3 time.Time      `json:"column_3"`
}

func (q *Queries) GetMetricsByURL(ctx context.Context, arg GetMetricsByURLParams) ([]Metric, error) {
	rows, err := q.db.QueryContext(ctx, getMetricsByURL, arg.UrlID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.UserID,
			&i.Browser,
			&i.Os,
			&i.Device,
			&i.Language,
			&i.Referrer,
			&i.Country,
			&i.Region,
			&i.City,
			&i.Utm,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
