// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ApiKey struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	LastUsed  sql.NullTime `json:"last_used"`
	CreatedAt time.Time    `json:"created_at"`
}

type Metric struct {
	ID        string          `json:"id"`
	UrlID     sql.NullString  `json:"url_id"`
	UserID    string          `json:"user_id"`
	Browser   sql.NullString  `json:"browser"`
	Os        sql.NullString  `json:"os"`
	Device    sql.NullString  `json:"device"`
	Language  sql.NullString  `json:"language"`
	Referrer  sql.NullString  `json:"referrer"`
	Country   sql.NullString  `json:"country"`
	Region    sql.NullString  `json:"region"`
	City      sql.NullString  `json:"city"`
	Utm       json.RawMessage `json:"utm"`
	Timestamp time.Time       `json:"timestamp"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Url struct {
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
	Shortcode   string          `json:"shortcode"`
	OriginalUrl string          `json:"original_url"`
	Notes       sql.NullString  `json:"notes"`
	Secret      sql.NullString  `json:"secret"`
	Active      bool            `json:"active"`
	Hit         int32           `json:"hit"`
	HitLimit    int32           `json:"hit_limit"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	Utm         json.RawMessage `json:"utm"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type UrlTag struct {
	UrlID string `json:"url_id"`
	TagID string `json:"tag_id"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Watchlist struct {
	ID        string         `json:"id"`
	Domain    string         `json:"domain"`
	Allowed   bool           `json:"allowed"`
	Note      sql.NullString `json:"note"`
	CreatedAt time.Time      `json:"created_at"`
}
