// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countAllURLs = `-- name: CountAllURLs :one
SELECT COUNT(*) FROM urls
`

func (q *Queries) CountAllURLs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllURLs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countURLsByUser = `-- name: CountURLsByUser :one
SELECT COUNT(*) FROM urls WHERE user_id = $1
`

func (q *Queries) CountURLsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countURLsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createURL = `-- name: CreateURL :one
INSERT INTO urls (id, user_id, shortcode, original_url, notes, secret, active, hit_limit, expires_at, utm)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, shortcode, original_url, notes, secret, active, hit, hit_limit, expires_at, utm, created_at, updated_at
`

type CreateURLParams struct {
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
	Shortcode   string          `json:"shortcode"`
	OriginalUrl string          `json:"original_url"`
	Notes       sql.NullString  `json:"notes"`
	Secret      sql.NullString  `json:"secret"`
	Active      bool            `json:"active"`
	HitLimit    int32           `json:"hit_limit"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	Utm         json.RawMessage `json:"utm"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.ID,
		arg.UserID,
		arg.Shortcode,
		arg.OriginalUrl,
		arg.Notes,
		arg.Secret,
		arg.Active,
		arg.HitLimit,
		arg.ExpiresAt,
		arg.Utm,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.Notes,
		&i.Secret,
		&i.Active,
		&i.Hit,
		&i.HitLimit,
		&i.ExpiresAt,
		&i.Utm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls WHERE id = $1
`

func (q *Queries) DeleteURL(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteURL, id)
	return err
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, user_id, shortcode, original_url, notes, secret, active, hit, hit_limit, expires_at, utm, created_at, updated_at FROM urls WHERE id = $1 LIMIT 1
`

func (q *Queries) GetURLByID(ctx context.Context, id string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByID, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.Notes,
		&i.Secret,
		&i.Active,
		&i.Hit,
		&i.HitLimit,
		&i.ExpiresAt,
		&i.Utm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLByShortcode = `-- name: GetURLByShortcode :one
SELECT id, user_id, shortcode, original_url, notes, secret, active, hit, hit_limit, expires_at, utm, created_at, updated_at FROM urls WHERE shortcode = $1 LIMIT 1
`

func (q *Queries) GetURLByShortcode(ctx context.Context, shortcode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByShortcode, shortcode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.Notes,
		&i.Secret,
		&i.Active,
		&i.Hit,
		&i.HitLimit,
		&i.ExpiresAt,
		&i.Utm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementHit = `-- name: IncrementHit :exec
UPDATE urls SET hit = hit + 1, updated_at=NOW() WHERE id = $1
`

func (q *Queries) IncrementHit(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementHit, id)
	return err
}

const listAllURLs = `-- name: ListAllURLs :many
SELECT id, user_id, shortcode, original_url, notes, secret, active, hit, hit_limit, expires_at, utm, created_at, updated_at FROM urls ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllURLsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllURLs(ctx context.Context, arg ListAllURLsParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listAllURLs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Shortcode,
			&i.OriginalUrl,
			&i.Notes,
			&i.Secret,
			&i.Active,
			&i.Hit,
			&i.HitLimit,
			&i.ExpiresAt,
			&i.Utm,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllURLsWithUser = `-- name: ListAllURLsWithUser :many
SELECT urls.id, urls.user_id, urls.shortcode, urls.original_url, urls.notes, urls.secret, urls.active, urls.hit, urls.hit_limit, urls.expires_at, urls.utm, urls.created_at, urls.updated_at, users.username AS created_by FROM urls
JOIN users ON urls.user_id = users.id
ORDER BY urls.created_at DESC LIMIT $1 OFFSET $2
`

type ListAllURLsWithUserParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllURLsWithUserRow struct {
	ID          string          `json:"id"`
	UserID      string          `json:"user_id"`
	Shortcode   string          `json:"shortcode"`
	OriginalUrl string          `json:"original_url"`
	Notes       sql.NullString  `json:"notes"`
	Secret      sql.NullString  `json:"secret"`
	Active      bool            `json:"active"`
	Hit         int32           `json:"hit"`
	HitLimit    int32           `json:"hit_limit"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	Utm         json.RawMessage `json:"utm"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	CreatedBy   string          `json:"created_by"`
}

func (q *Queries) ListAllURLsWithUser(ctx context.Context, arg ListAllURLsWithUserParams) ([]ListAllURLsWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllURLsWithUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllURLsWithUserRow
	for rows.Next() {
		var i ListAllURLsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Shortcode,
			&i.OriginalUrl,
			&i.Notes,
			&i.Secret,
			&i.Active,
			&i.Hit,
			&i.HitLimit,
			&i.ExpiresAt,
			&i.Utm,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByUser = `-- name: ListURLsByUser :many
SELECT id, user_id, shortcode, original_url, notes, secret, active, hit, hit_limit, expires_at, utm, created_at, updated_at FROM urls WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListURLsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListURLsByUser(ctx context.Context, arg ListURLsByUserParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Shortcode,
			&i.OriginalUrl,
			&i.Notes,
			&i.Secret,
			&i.Active,
			&i.Hit,
			&i.HitLimit,
			&i.ExpiresAt,
			&i.Utm,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls SET original_url=$2, notes=$3, secret=$4, active=$5, hit_limit=$6, expires_at=$7, utm=$8, updated_at=NOW()
WHERE id=$1 RETURNING id, user_id, shortcode, original_url, notes, secret, active, hit, hit_limit, expires_at, utm, created_at, updated_at
`

type UpdateURLParams struct {
	ID          string          `json:"id"`
	OriginalUrl string          `json:"original_url"`
	Notes       sql.NullString  `json:"notes"`
	Secret      sql.NullString  `json:"secret"`
	Active      bool            `json:"active"`
	HitLimit    int32           `json:"hit_limit"`
	ExpiresAt   sql.NullTime    `json:"expires_at"`
	Utm         json.RawMessage `json:"utm"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL,
		arg.ID,
		arg.OriginalUrl,
		arg.Notes,
		arg.Secret,
		arg.Active,
		arg.HitLimit,
		arg.ExpiresAt,
		arg.Utm,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Shortcode,
		&i.OriginalUrl,
		&i.Notes,
		&i.Secret,
		&i.Active,
		&i.Hit,
		&i.HitLimit,
		&i.ExpiresAt,
		&i.Utm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
