// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlist.sql

package db

import (
	"context"
	"database/sql"
)

const createWatchlistEntry = `-- name: CreateWatchlistEntry :one
INSERT INTO watchlist (id, domain, allowed, note)
VALUES ($1, $2, $3, $4)
RETURNING id, domain, allowed, note, created_at
`

type CreateWatchlistEntryParams struct {
	ID      string         `json:"id"`
	Domain  string         `json:"domain"`
	Allowed bool           `json:"allowed"`
	Note    sql.NullString `json:"note"`
}

func (q *Queries) CreateWatchlistEntry(ctx context.Context, arg CreateWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, createWatchlistEntry,
		arg.ID,
		arg.Domain,
		arg.Allowed,
		arg.Note,
	)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Allowed,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWatchlistEntry = `-- name: DeleteWatchlistEntry :exec
DELETE FROM watchlist WHERE id = $1
`

func (q *Queries) DeleteWatchlistEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWatchlistEntry, id)
	return err
}

const getWatchlistByDomain = `-- name: GetWatchlistByDomain :one
SELECT id, domain, allowed, note, created_at FROM watchlist WHERE domain = $1 LIMIT 1
`

func (q *Queries) GetWatchlistByDomain(ctx context.Context, domain string) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, getWatchlistByDomain, domain)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Allowed,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listWatchlist = `-- name: ListWatchlist :many
SELECT id, domain, allowed, note, created_at FROM watchlist ORDER BY created_at DESC
`

func (q *Queries) ListWatchlist(ctx context.Context) ([]Watchlist, error) {
	rows, err := q.db.QueryContext(ctx, listWatchlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watchlist
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Allowed,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
