DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS watchlist;
DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS url_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
